### ISSUE TITLE
ASCII extended character set disappeared after update to 9.19.0

### ISSUE THREAD

**Issue by wilya7** [BitBoxSwiss/bitbox02-firmware#1254]
Fyi, the feature is now released in firmware v4.2.1, which can be installed with the [BitBoxApp](https://shiftcrypto.ch/start/).

_Originally posted by @benma in https://github.com/BitBoxSwiss/bitbox02-firmware/issues/151#issuecomment-547441007_

**Comment by wilya7** [comment]
This is a serious problem. Since last firmware release, the ASCII extended character set is not anymore available. This makes accessing the wallet impossible for anyone adopting the 25th word with extended characters set.

**Comment by wilya7** [comment]
My apologies. I made a stupid mistake. The character set is still there. Closing the issue.

**Comment by benma** [comment]
You may have confused the device password with the optional passphrase. Only the optional passphrase has a special chars keyboard.
