### ISSUE TITLE
Security concept of the secure element

### ISSUE THREAD

**Issue by MaJerle** [BitBoxSwiss/bitbox02-firmware#1307]
I've already asked a question before, which was not fully answered, but partially. [Link to first discussion](https://github.com/BitBoxSwiss/bitbox02-firmware/issues/1160)

I'm reading the BitBox02 security concept again. There is a nice picture on your blog:
![image](https://github.com/user-attachments/assets/bc2fae8d-a765-46ec-acff-9437efffaf6f)

In the previous issue (link above), @benma mentioned:
> The answer lies in the picture you added actually. The secure chip receives the hash of your device password (so not your password), and applies KDF to it with internal keys. The output is then again hmac'd with your password, which results in the final encryption key. This means that the secure chip (and the communication line to the MCU) never have the seed nor the encryption key of the encrypted seed.

In your blog, you claim that if an attacker has access and performs reverse engineering in a country where it is legal, you want to be protected from this. Me, as an attacker, if I sniff I2C lines:

- I get `sha256(S || P)`
- Secure chip will send back `K`, that is derived from the `KDF(sha256(S || P) || secure_chip_random_key)`
- Finally, MCU will perform `hmac(sha256(S || P), K)` with inner and outer keys, that are stored (according to the comment above)

As I understand:
- System is as secure as your password
- Secure element is there only to go through it to prevent fast brute force attacks and to limit to cca 750k attempts.

Finally, in your marketing, you mention there is attestation key for device geniune check.
- Where is the private key stored, that makes sure one cannot clone the device? Is it in the secure element?
- Is secure element preloaded during your manufacturing with device certificate and private key?

**Comment by benma** [comment]
> I've already asked a question before, which was not fully answered, but partially. [Link to first discussion](https://github.com/BitBoxSwiss/bitbox02-firmware/issues/1160)
> 
> I'm reading the BitBox02 security concept again. There is a nice picture on your blog: ![image](https://private-user-images.githubusercontent.com/405717/369604934-bc2fae8d-a765-46ec-acff-9437efffaf6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5OTAwMzcsIm5iZiI6MTcyNjk4OTczNywicGF0aCI6Ii80MDU3MTcvMzY5NjA0OTM0LWJjMmZhZThkLWE3NjUtNDZlYy1hY2ZmLTk0MzdlZmZmYWY2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQwNzIyMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDM5ODUzZjgxZTlmOWMzOGNiMWUwY2QyZGM0ODRmZTk1MTA4ODA4NjBiODNiNzgzMDY2ZjhhNzIzZmE4NWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TjudNfmpQzCcadoy8xqRLl18R1SxsaXGSUFhAf1awBo)
> 
> In the previous issue (link above), @benma mentioned:
> 
> > The answer lies in the picture you added actually. The secure chip receives the hash of your device password (so not your password), and applies KDF to it with internal keys. The output is then again hmac'd with your password, which results in the final encryption key. This means that the secure chip (and the communication line to the MCU) never have the seed nor the encryption key of the encrypted seed.
> 
> In your blog, you claim that if an attacker has access and performs reverse engineering in a country where it is legal, you want to be protected from this. Me, as an attacker, if I sniff I2C lines:
> 
>     * I get `sha256(S || P)`
> 
>     * Secure chip will send back `K`, that is derived from the `KDF(sha256(S || P) || secure_chip_random_key)`
> 
>     * Finally, MCU will perform `hmac(sha256(S || P), K)` with inner and outer keys, that are stored (according to the comment above)
> 
> 
> As I understand:
> 
>     * System is as secure as your password
> 
>     * Secure element is there only to go through it to prevent fast brute force attacks and to limit to cca 750k attempts.
> 
> 
> Finally, in your marketing, you mention there is attestation key for device geniune check.
> 
>     * Where is the private key stored, that makes sure one cannot clone the device? Is it in the secure element?
> 
>     * Is secure element preloaded during your manufacturing with device certificate and private key?

The device attestation private key is stored in the secure chip. The private key is generated during manufacturing inside the chip. The certificate is created and put on the device flash memory during manufacturing.

**Comment by benma** [comment]
I'll close this as it's not actually a firmware issue. Please re-open if I am mistaken. Thanks.
