### ISSUE TITLE
Bug: Regtest and Signet: Incorrect addresses

### ISSUE THREAD

**Issue by andreasgriffin** [BitBoxSwiss/bitbox02-firmware#1318]
The regtest descriptor: `wsh(sortedmulti(1,[3bceb0d1/48h/1h/0h/2h]tpubDEfDLjt9KPzMJRAVqD6SDETg6ErTpGcrwiqgoPRiKuVjZn5ZXSnmXdZuj7mQZ8SNqQTZLoiPpcRwCiqQkt7kUUQFNfpifyA9wTnLJ8ChYJT/<0;1>/*,[3dcb0605/48h/1h/0h/2h]tpubDFdsrUN9ZC54Qp3qG7dHK2u16GFjzVtqq4MJY1Srt4vV6BBDmgL5nkBCKguvs4LEt664D1KjMcgaiq66E4iEUwS1hVisKjArGmBtVpxF78C/<0;1>/*))#6dp46rpc`
gives as first address `bcrt1qzsv4g3w6zy5v4usgc9pq2rrfra7nkj0ppsk3w8337ss35tz7rfeq3mpv5m`

When this is validated on the bitbox via hwi  [display_multisig_address](https://hwi.readthedocs.io/en/latest/devices/index.html#hwilib.devices.ledger.LedgerClient.display_multisig_address)  one gets an address that is _almost_ identical, but the last few characters are different:

![image](https://github.com/user-attachments/assets/0423c5cc-c3f2-4663-bf02-d61b61df4bc0)

This issue is in REGTEST and SIGNET, but not TESTNET3 and mainnet (afaik)

**Comment by andreasgriffin** [comment]
I got it... this is actually the testnet3 address.   Bitbox02 doesnt seem to support regtest...

**Comment by benma** [comment]
Thanks. It does since https://github.com/BitBoxSwiss/bitbox02-firmware/releases/tag/firmware%2Fv9.21.0, which will be released with the BitBoxApp soon. 

Which wallet/library are you using? Regtest support might need to be integrated there too.

**Comment by andreasgriffin** [comment]
I use bdk (regtest supported) and hwi and wrap it https://github.com/andreasgriffin/bitcoin-usb  for my bitcoin wallet https://github.com/andreasgriffin/bitcoin-safe
